### ISSUE TITLE
interface 'wl_surface' has no event 2 (Arch linux + hyprland, window failing to stay open)

### ISSUE THREAD

**Issue by CrazieNewb** [QuantumBadger/Speedy2D#112]
On arch linux with hyprland and wayland. Running the helloworld example outputs:
```
❯ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s
     Running `target/debug/speedy_2d_interface`
ERROR [speedy2d::window_internal_glutin] Couldn't find primary monitor. Using first available monitor.
DEBUG [speedy2d::window_internal_glutin] Monitor #0 (primary): 0x07CB (BOE)
INFO [speedy2d::window_internal_glutin] Trying vsync=true, multisampling=16...
INFO [speedy2d::window_internal_glutin] Context created
INFO [speedy2d::window_internal_glutin] Centering window. Monitor size: PhysicalSize { width: 1920, height: 1080 }. Window outer size: PhysicalSize { width: 640, height: 240 }.
INFO [speedy2d::window_internal_glutin] Centering window. Monitor size: PhysicalSize { width: 1920, height: 1080 }. Window outer size: PhysicalSize { width: 640, height: 240 }.
INFO [speedy2d::window_internal_glutin] Using OpenGL version: 4.6 (Compatibility Profile) Mesa 24.0.3-arch1.1
INFO [speedy2d::glbackend] GL debug log enabled for glow backend
INFO [speedy2d::glwrapper] GL context manager created
INFO [speedy2d::renderer2d] Creating vertex shader
INFO [speedy2d::renderer2d] Using OpenGL 2.0 shaders
INFO [speedy2d::renderer2d] Creating fragment shader
INFO [speedy2d::renderer2d] Compiling program
INFO [speedy2d::glwrapper] Setting viewport size to 640x240
INFO [speedy2d::window_internal_glutin] Resized: PhysicalSize { width: 960, height: 1030 }
INFO [speedy2d::glwrapper] Setting viewport size to 960x1030
INFO [speedy2d::font_cache] No more space in existing textures (0). Creating new.
interface 'wl_surface' has no event 2
INFO [speedy2d::glwrapper] GL context manager is now inactive
```

**Comment by QuantumBadger** [comment]
Thanks for the report -- the example works for me in Weston on Arch.

Does it work after a `cargo update`? If not, could you give details on which GPU and driver you're using please?

**Comment by CrazieNewb** [comment]
After 'cargo update' to update from 2.0.0 to 2.1.0 nothing has changed.
My CPU is `11th Gen i3-1115G4` and i have no GPU. The example worked on the same laptop on windows 11 if that helps narrow it down.

**Comment by JustLinuxUser** [comment]
I am having the same issue, and have been having it for a long time. I am on latest hyprland installed, and latest Speedy 2d version, just installed it with `cargo add speedy2d`. I also checked the winit crate, and the current latest version works perfectly, but not sure where this error is comming from

**Comment by JustLinuxUser** [comment]
I have some bad news! :smile: I think this crate needs to be updated up to lates glutin (which is rewritten from scratch) for this issue to go away. Good luck

**Comment by ericsink** [comment]
Digression:  The other side of that bad news is that glutin dropped support for iOS in that rewrite.  Speedy2D doesn't support iOS yet anyway, but still...

**Comment by JustLinuxUser** [comment]
For anyone struggling with this, you can set `WINIT_UNIX_BACKEND=x11` and run the app in x11 mode, still works 
(Still hoping the update to new glutin is possible)

**Comment by QuantumBadger** [comment]
Thanks for the details everyone. I've gone ahead and rewritten Speedy2D's window handling code to use the latest version of Glutin!

https://github.com/QuantumBadger/Speedy2D/commit/3159dd1d92bd6d3771b94c7eede0295359ed6372

@JustLinuxUser / @CrazieNewb Could you try the latest version of Speedy2D from the `master` branch please, to check if this resolves the issue?

```toml
speedy2d = { git = "https://github.com/QuantumBadger/Speedy2D.git" }
```

**Comment by JustLinuxUser** [comment]
I am so sorry, but no, still having this issue! Here is the backtrace:
```
thread 'main' panicked at /home/andriy/.cargo/git/checkouts/speedy2d-f61a7bd07eee4969/ba5abfc/src/window_internal_glutin.rs:696:20:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/panicking.rs:72:14
   2: core::panicking::panic
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/panicking.rs:145:5
   3: core::option::unwrap_failed
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/option.rs:1985:5
   4: core::option::Option<T>::unwrap
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/option.rs:933:21
   5: speedy2d::window_internal_glutin::gl_config_picker
             at /home/andriy/.cargo/git/checkouts/speedy2d-f61a7bd07eee4969/ba5abfc/src/window_internal_glutin.rs:696:5
   6: core::ops::function::FnOnce::call_once
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/ops/function.rs:250:5
   7: glutin_winit::DisplayBuilder::build
             at /home/andriy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/glutin-winit-0.4.2/src/lib.rs:126:13
   8: speedy2d::window_internal_glutin::create_best_context
             at /home/andriy/.cargo/git/checkouts/speedy2d-f61a7bd07eee4969/ba5abfc/src/window_internal_glutin.rs:718:22
   9: speedy2d::window_internal_glutin::WindowGlutin<UserEventType>::new
             at /home/andriy/.cargo/git/checkouts/speedy2d-f61a7bd07eee4969/ba5abfc/src/window_internal_glutin.rs:386:13
  10: speedy2d::Window<UserEventType>::new_with_user_events
             at /home/andriy/.cargo/git/checkouts/speedy2d-f61a7bd07eee4969/ba5abfc/src/lib.rs:1433:27
  11: speedy2d::Window::new_with_options
             at /home/andriy/.cargo/git/checkouts/speedy2d-f61a7bd07eee4969/ba5abfc/src/lib.rs:1419:9
  12: speedy2d::Window::new_centered
             at /home/andriy/.cargo/git/checkouts/speedy2d-f61a7bd07eee4969/ba5abfc/src/lib.rs:1390:9
  13: day17_2::main
             at ./src/main.rs:240:18
  14: core::ops::function::FnOnce::call_once
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by JustLinuxUser** [comment]
and `WINIT_UNIX_BACKEND=x11 cargo run` doesn't work either now. Same error

**Comment by Aworldc** [comment]
> I am so sorry, but no, still having this issue! Here is the backtrace:

weird, `speedy2d = { git = "https://github.com/QuantumBadger/Speedy2D.git" }` fixes it for me.

NixOs + Hyprland.

**Comment by JustLinuxUser** [comment]
I just tried again, and still:
```2025-03-07T20:51:28.442Z DEBUG [sctk] Bound new global [53] wl_output v4
2025-03-07T20:51:28.442Z DEBUG [sctk] Bound new global [9] zxdg_output_manager_v1 v3
2025-03-07T20:51:28.442Z DEBUG [sctk] Bound new global [1] wl_seat v7
2025-03-07T20:51:28.446Z DEBUG [sctk] Bound new global [10] wp_cursor_shape_manager_v1 v1
2025-03-07T20:51:28.446Z DEBUG [sctk] supported wl_shm format Argb8888
2025-03-07T20:51:28.446Z DEBUG [sctk] supported wl_shm format Xrgb8888
2025-03-07T20:51:28.446Z DEBUG [sctk] supported wl_shm format Xbgr8888
2025-03-07T20:51:28.446Z DEBUG [sctk] supported wl_shm format Abgr8888
2025-03-07T20:51:28.446Z DEBUG [sctk] supported wl_shm format Xrgb2101010
2025-03-07T20:51:28.446Z DEBUG [sctk] supported wl_shm format Argb2101010
2025-03-07T20:51:28.446Z DEBUG [sctk] supported wl_shm format Xbgr2101010
2025-03-07T20:51:28.446Z DEBUG [sctk] supported wl_shm format Abgr2101010
2025-03-07T20:51:28.446Z TRACE [calloop::loop_logic] [calloop] Inserting new source #0
2025-03-07T20:51:28.446Z TRACE [calloop::loop_logic] [calloop] Inserting new source #1
2025-03-07T20:51:28.446Z TRACE [calloop::loop_logic] [calloop] Inserting new source #2
2025-03-07T20:51:28.447Z ERROR [speedy2d::window_internal_glutin] Couldn't find primary monitor. Using first available monitor.
2025-03-07T20:51:28.447Z DEBUG [speedy2d::window_internal_glutin] Monitor #0 (primary): eDP-1
2025-03-07T20:51:28.447Z INFO  [speedy2d::window_internal_glutin] Trying multisampling=16...

thread 'main' panicked at /home/andrii/.cargo/git/checkouts/speedy2d-8114d88afcb07d3b/5e8a885/src/window_internal_glutin.rs:696:20:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0: rust_begin_unwind
             at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library/std/src/panicking.rs:692:5
   1: core::panicking::panic_fmt
             at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library/core/src/panicking.rs:75:14
   2: core::panicking::panic
             at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library/core/src/panicking.rs:145:5
   3: core::option::unwrap_failed
             at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library/core/src/option.rs:2015:5
   4: core::option::Option<T>::unwrap
             at /home/andrii/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/option.rs:978:21
   5: speedy2d::window_internal_glutin::gl_config_picker
             at /home/andrii/.cargo/git/checkouts/speedy2d-8114d88afcb07d3b/5e8a885/src/window_internal_glutin.rs:696:5
   6: core::ops::function::FnOnce::call_once
             at /home/andrii/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
   7: glutin_winit::DisplayBuilder::build
             at /home/andrii/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/glutin-winit-0.4.2/src/lib.rs:126:13
   8: speedy2d::window_internal_glutin::create_best_context
             at /home/andrii/.cargo/git/checkouts/speedy2d-8114d88afcb07d3b/5e8a885/src/window_internal_glutin.rs:718:22
   9: speedy2d::window_internal_glutin::WindowGlutin<UserEventType>::new
             at /home/andrii/.cargo/git/checkouts/speedy2d-8114d88afcb07d3b/5e8a885/src/window_internal_glutin.rs:386:13
  10: speedy2d::Window<UserEventType>::new_with_user_events
             at /home/andrii/.cargo/git/checkouts/speedy2d-8114d88afcb07d3b/5e8a885/src/lib.rs:1433:27
  11: speedy2d::Window::new_with_options
             at /home/andrii/.cargo/git/checkouts/speedy2d-8114d88afcb07d3b/5e8a885/src/lib.rs:1419:9
  12: speedy2d::Window::new_centered
             at /home/andrii/.cargo/git/checkouts/speedy2d-8114d88afcb07d3b/5e8a885/src/lib.rs:1390:9
  13: speedy_2d_test::main
             at ./src/main.rs:27:18
  14: core::ops::function::FnOnce::call_once
             at /home/andrii/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

I am using Hyprland 0.47.2

**Comment by Aworldc** [comment]
hmm, i'm on Hyprland 0.41.2.

**Comment by JustLinuxUser** [comment]
Actually I figured out why it is crashing out. It tries to the best multisampling config possible starting at 16, calling the function DisplayBuilder::build(), which crashes if there wasn't a config with the correct requirements found, and the API doesn't really allow for a better method of handling this. If you manually create a window, setting the options that disable multisampling, or setting an multisampling option that your PC supports, it just works.

**Comment by QuantumBadger** [comment]
@JustLinuxUser Yes that's correct -- it's effectively a bug in `glutin-winit` calling `config_picker` with zero options, but then forcing you to pick an option (which is impossible).

Not sure if this is still an issue in the latest `glutin-winit` version (a quick glance suggests it is), and I'm considering just copying the "glue" code from the library directly as there's not very much of it.

**Comment by QuantumBadger** [comment]
This should finally be fixed in v3.0.0 -- please let me know if this works for you!

**Comment by JustLinuxUser** [comment]
> This should finally be fixed in v3.0.0 -- please let me know if this works for you!

It is fixed!!
